### ISSUE TITLE
subfunctions of ATOMIX_load

### ISSUE THREAD

**Issue by ilkerf** [SCOR-ATOMIX/shear-probes#1]
Thanks for organizing this Kiki!
Because I aimed to supply one load function at the time (through the wiki), I put Cynthia's load_netcdf_data and other dependencies as subfunctions in it.
Now that we have a repository, we can pull them out and track them separately, if you want.
This can be needed if Cynthia wants to update etc. the load_netcdf function.

**Comment by KikiSchulz** [comment]
Wow, it took me 2 month to see this, while searching for some other functionality. I will take care of it soon!

**Comment by KikiSchulz** [comment]
done :) we'll have to discuss folder structure during meeting still
